Traceback (most recent call last):
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/resources/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/resources/.pyenv/versions/3.8.12/envs/ekonml38/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ekorpkit import eKonf
eKonf.dependencies()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mekorpkit[39;00m [38;5;28;01mimport[39;00m eKonf
[0;32m----> 2[0m [43meKonf[49m[38;5;241;43m.[39;49m[43mdependencies[49m[43m([49m[43m)[49m

[0;31mTypeError[0m: dependencies() missing 1 required positional argument: '_key'
TypeError: dependencies() missing 1 required positional argument: '_key'

